# .github/workflows/deploy-pages.yml

name: Deploy Static Site to GitHub Pages

on:
  # Runs on pushes to the "main" branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # The build job doesn't actually "build" anything here, it just prepares the files
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site files as an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This uploads everything from the root of your repository,
          # which is exactly what you need for this project.
          path: .

  # The deploy job takes the artifact and pushes it to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job runs only after the 'build' job is successful
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
